version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: inventory-backend:latest
    ports:
      - "8080:8080"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: inventory-frontend:latest
    ports:
      - "3000:80"
    restart: unless-stopped
